version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: ileka2468/rfa-backend:latest
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_IN_MS: ${JWT_EXPIRATION_IN_MS}
      REFRESH_TOKEN_EXPIRATION_IN_MS: ${REFRESH_TOKEN_EXPIRATION_IN_MS}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: ileka2468/rfa-frontend:latest
    ports:
      - "80:80"
    environment:
      REACT_APP_API_URL: http://backend:8080
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443" # For https
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
