services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: ileka2468/rfa-backend:latest
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_IN_MS: ${JWT_EXPIRATION_IN_MS}
      REFRESH_TOKEN_EXPIRATION_IN_MS: ${REFRESH_TOKEN_EXPIRATION_IN_MS}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: ileka2468/rfa-frontend:latest
    volumes:
      - frontend_dist:/app/dist:rw
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_dist:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/ssl:ro # https
    depends_on:
      - frontend
      - backend

volumes:
  frontend_dist:
