### @name local
@baseUrl = http://localhost:8080


# Test API REGISTER
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "username":  "Test",
  "password":  "Test",
  "firstName": "Test",
  "lastName":  "Test"
}

> {%
    if (response.status !== 200) {
        throw new Error("Register Test failed: expected status 200, got " + response.status);
    }
%}

###

POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "Test",
  "password": "Test"
}

> {%
     if (response.status != 200) {
         throw new Error("Login Test Failed: expected status 200 got " + response.status)
     }

     console.log("Returned access token in Auth header: " + response.headers.valueOf("Authorization"))
     console.log("Cookies Set: " + response.headers.valueOf("Set-Cookie"))
  %}

###
POST {{baseUrl}}/api/matches/run
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJUZXN0Iiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfVVNFUiJ9XSwiaWF0IjoxNzI3MDgyMDY0LCJleHAiOjE3MjcwODIxMjR9._f-KI3C0iuzrJIdee0h2R1WtLxeusOUjNGtrLMcVRbeQpnU8o6-vmo2G_cYRz8xTDZLCgfU0x46D0JmiKIHSxg
