name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build and Deploy via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -ex
            cd se452-group-project/
            git fetch origin main
            git reset --hard origin/main

            # Build the frontend container and extract built files
            docker build -t rfa-frontend ./Frontend
            docker create --name frontend_build_temp rfa-frontend

            # Clean up previous build files
            rm -r ~/rfadeploydev/dist

            # Copy the new build files to the host machine
            docker cp frontend_build_temp:/app/dist ~/rfadeploydev/
            docker rm frontend_build_temp

            # Copy over nginx conf and docker compose file
            rm -f ~/rfadeploydev/default.conf
            rm -f ~/rfadeploydev/docker-compose.yml
            cp ./default.conf ~/rfadeploydev/
            cp ./docker-compose.yml ~/rfadeploydev/

            # Build new images and push to dockerhub
            docker system prune -f
            docker compose build --no-cache
            docker compose push

            # Enter deployment directory, pull image and start.
            cd ~/rfadeploydev/
            docker compose pull
            docker compose up -d --force-recreate
